<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->


<!-- Mirrored from www.ipu.ac.in/infox15/backgear.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 08 Mar 2016 20:02:00 GMT -->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="description" content="infox usict infoxpression technical fest ggsipu ipu march festival">
	<meta name="author" content="Ankit Jain">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>BackGear - InfoXpression 2015</title>

	<link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico" />
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/animate.css">
	<link rel="stylesheet" href="css/owl.carousel.css">
	<link rel="stylesheet" href="css/main.css">
	<link rel="stylesheet" href="css/responsive.css">

	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,200' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Oswald:400,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

	<script src="js/modernizr-2.6.2.min.js"></script>
</head>

<body class="blog-page">
	<div id="loading-mask">
		<div class="loading-img">
			<img alt="Preloader" src="img/preloader.gif" />
		</div>
	</div>

	<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="index-2.html">
					<h1 id="logo">
							<img src="img/logo-infox.png" >
						</h1>
				</a>
			</div>

			<nav class="collapse navbar-collapse navbar-right" role="Navigation">
				<ul id="nav" class="nav navbar-nav">
					<li><a href="index-2.html">Home</a>
					</li>
					<li><a href="index-2.html#about">About</a>
					</li>
					<li><a href="index-2.html#schedule">Schedule</a>
					</li>
					<li class="current"><a href="index-2.html#event">Events</a>
					</li>
					<li><a href="index-2.html#team">Team</a>
					</li>
					<li><a href="index-2.html#sponsors">Sponsors</a>
					</li>
					<li><a href="index-2.html#contact">Contact Us</a>
					</li>
				</ul>
			</nav>
		</div>
	</header>

	<section id="blog-banner">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<div class="blog-title">
						<h2>BACKGEAR</h2>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section id="blog-page">
		<div class="container">
			<div class="row">
				<div id="blog-posts" class="col-md-8 col-sm-8">
					<div class="post-item">
						<article class="entry wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="post-thumb">
								<a href="single-post.html">
									<img src="img/event/backgear.jpg" class="img-responsive">
								</a>
							</div>
							<br>
							<div class="post-excerpt">
								<p><strong>About</strong>
								</p>
								<p>Participants are given an executable (.exe file)&nbsp; and are asked to do reverse coding, that is to develop&nbsp;the source code which generates the same output as generated by the executable .</p>
								<p>The participants are expected to solve certain pattern based, logical and algorithmic problems using C and C++.</p>
								<p><strong>Rules</strong>
								</p>
								<ol style="margin: 0 0 0 20px; list-style: decimal">
									<li>The contest is divided into three phases.</li>
									<li>Participants must participate individually.</li>
									<li>All participants will be called on campus for all the phases.</li>
									<li>Any form of malpractice shall lead to disqualification of the participant(s).</li>
									<li>The decision of the authorities shall be final and binding.</li>
									<li>In case of tie, the time of submission will be considered to decide the winner.</li>
								</ol><br>
								<p><strong>Eligibility</strong>
								</p>
								<p>All the students studying in colleges in India are eligible for the participation.</p>
								<br>
							</div>
						</article>

						<div class="next-prev clearfix">
							<a href="almightee.html" class="prev-post">
								<i class="fa fa-angle-left fa-2x"></i>Previous Event
							</a>
							<a href="bootstrapp.html" class="next-post pull-right">
									Next Event<i class="fa fa-angle-right fa-2x"></i>
								</a>
						</div>
					</div>
				</div>

				<div id="right-sidebar" class="col-md-4 col-sm-4">
					<aside class="widget wow fadeInDown">
						<div class="form-group">
                        	<a href="https://docs.google.com/a/ipu.ac.in/forms/d/1gxDDb1qClWnDHHgHGXfFMtpvE5PTViOgRtdA3iCPyQs/viewform" type="submit" id="post-comment" value="Register" class="btn btn-transparent">Register</a>
                        </div>
						<div class="author-about clearfix">
							<h4>Coordinators</h4>
							<div class="post-author pull-left">
								<img src="img/blog/avatar.png" alt="">
							</div>
							<div class="author-bio">
								<h3> Jasvinder </h3>
								<p>+919560052722</p>
							</div>
						</div>
						<div class="author-about clearfix">
							<div class="post-author pull-left">
								<img src="img/blog/avatar.png" alt="">
							</div>
							<div class="author-bio">
								<h3> Mukul </h3>
								<p>+919999386541</p>
							</div>
						</div>
					</aside>
				</div>
			</div>
		</div>
	</section>

	<footer id="footer" class="bg-one">
		<div class="container">
			<div class="row wow fadeInUp" data-wow-duration="500ms">
				<div class="col-lg-12">
					<div class="social-icon">
						<ul>
							<li><a href="https://play.google.com/store/apps/details?id=com.infox.dhruv.techfest"><i class="fa fa-android"></i></a>
							</li>
							<li><a href="https://www.facebook.com/infoxpression?_rdr"><i class="fa fa-facebook"></i></a>
							</li>
							<li>
								<p align="left"> Guru Gobind Singh Indraprastha University, Sector 16C, Dwarka
									<br> infox@ipu.ac.in</p>
							</li>
						</ul>
					</div>
					<div class="copyright text-center">
						<img src="img/logo-infox.png">
						<br />
						<p>Copyright &copy; 2015. All Rights Reserved.</p>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<a href="#" id="scrollUp"><i class="fa fa-angle-up fa-2x"></i></a>

	<script src="js/jquery-1.11.0.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.scrollUp.min.html"></script>
	<script src="js/classie.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<script src="js/jquery.nicescroll.min.js"></script>
	<script src="js/jquery.easing-1.3.pack.js"></script>
	<script src="js/wow.min.js"></script>
	<script src="js/jquery.fitvids.js"></script>
	<script src="js/custom.js"></script>
</body>


<!-- Mirrored from www.ipu.ac.in/infox15/backgear.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 08 Mar 2016 20:02:01 GMT -->
</html>
